
from datetime import datetime

current_date = datetime.now().strftime('%Y-%m-%d')

#current_date = "2024-11-29"

is_backtest = True # True  False

event = {

    "assets": [
        "IWO",
        "VBK",
        "ROBO",
        "QCLN",
        "ICLN",
        "VNQ",
        "IAU",
        "EDV",
        "SHV",
        "IGLB",
        "VCLT",
        "LQD",
        "VCIT",
        "ARKK",
        "SCHD",
        "VIG",
        "SHY",
        "VCSH",
        "TLT",
        "DVY",
        "SDY",
        "SPLG",
        "ARKW",
        "IJT",
        "MUB",
        "SHM",
        "RSP",
        "PRF",
        "HYG",
        "ANGL",
        "EZU",
        "IEUR",
        "SJNK",
        "RPG",
        "GVI",
        "FPX",
        "SLYG",
        "FVD",
        "RDVY",
        "EWU",
        "EWD",
        "DES",
        "TLH",
        "FDL",
        "QQEW",
        "RPV",
        "IWC",
        "PTH",
        "KSA",
        "AMLP",
        "MLPX",
        "BND",
        "GTO",
        "EES",
        "DWAS",
        "KIE",
        "FEZ",
        "FLEE",
        "RZV",
        "IJS",
        "XSVM",
        "XLE",
        "PXI",
        "TAN",
        "FDN",
        "SOCL",
        "GRID",
        "DBC",
        "COM",
        "EWY",
        "EWN",
        "EWT",
        "FXI",
        "GXC",
        "EFV",
        "FGD",
        "BWX",
        "HYEM",
        "UNG",
        "VNQI",
        "RWX",
        "KWEB",
        "CHIQ",
        "IGF",
        "NFRA",
        "ASHR",
        "CQQQ",
        "MCHI",
        "CXSE",
        "PGJ",
        "VEU",
        "CWI",
        "EMGF",
        "AAXJ",
        "AIA",
        "EPP",
        "VPL",
        "GMF",
        "EEM",
        "SPEM",
        "VWO",
        "GEM",
        "DLS",
        "EFG",
        "EMB",
        "VWOB",
        "DXJ",
        "EWJ",
        "HEWJ",
        "SPY",
        "VOO",
        "IVV",
        "VBMFX",
        "GBF",
        "SH",
        "AGG",
        "SRS",
        "EFU",
        "TZA",
        "SDOW",
        "GLD",
        "BIL",
        "TBT",
        "IEF",
        "SLX",
        "PBD",
        "IGBH",
        "PZA",
        "VYMI",
        "EWL",

    ],


    "Model_Assets": [
        "IWO",  # "VBK", 
        "ROBO",
        "QCLN",
        "ICLN",
        "VNQ",
        "IAU",
        "EDV",
        "SHV",
        "VCLT", #"IGLB", 
        "VCIT", #"LQD",  
        "ARKK",
        "VIG",
        "VCSH",
        "TLT",
        "SDY",
        "SPLG",
        "ARKW",
        "IJT",
        "MUB", # "SHM"
        "RSP", # "PRF"
        "HYG", # "ANGL"
        "EZU", # "IEUR"
        #"SHM",
        #"PRF",
        #"ANGL",
        #"IEUR",
        "SJNK",
        "RPG",
        "GVI",
        "PZA",
        "FPX",
        "SLYG",
        #"FVD", # "RDVY"
        "EWU", # "EWD"
        "EWD",
        #"RDVY",
        "EWL",
        "DES",
        "TLH",
        "FDL",
        "QQEW",
        "RPV",
        "IWC",
        "PTH",
        "IGBH",
        "KSA",
        "MLPX",
        "GTO",
        "EES",
        "DWAS",
        "KIE",
        "FLEE",
        "RZV",
        "XSVM",
        "IJS", # "XSVM"
        "PXI",
        #"XLE", # "PXI"
        "TAN",
        "PBD",
        "SLX",
        "SOCL",
        "GRID",
        "DBC",
        "EWY",
        "EWN",
        "EWT",
        "GXC",
        "EFV",
        "FGD",
        "BWX",
        "HYEM",
        "UNG",
        "RWX",
        #"VNQI", # "RWX"
        "KWEB",
        "CHIQ",
        #"IGF",
        "IGF", # "NFRA"
        #"NFRA",
        "FXI",
        "ASHR",
        "CQQQ",
        "CXSE",
        #"MCHI", # "CXSE"
        "PGJ",
        "VEU",
        "CWI",
        "EMGF",
        "AIA",
        "AAXJ", # "AIA"
        "EPP",
        "GMF",
        "SPEM",
        "VYMI",
        "GEM",
        "DLS",
        "EFG",
        "VWOB",
        "DXJ",
        "HEWJ",
        "EEM",
    ],

    "Emergency_Assets_All": [
        "SPY",
        "VOO",
        "IVV",
        "IEF",
        #"VBMFX",
        "BND",
        "GBF",
        "^IRX",
        "SH",
        "TLT",
        "AGG",
        "SRS",
        "EFU",
        "TZA",
        "SDOW",
        "GLD",
        "BIL",
        "TBT"
    ],

    "Equity_Signal_Assets_List": [
        "SPY",
        "VOO",
        "IVV"
    ],

    "Bond_Signal_Assets_List": [
        "IEF",
        "BND",
        "GBF"
    ],

    "BackUp_Emergency_Assets": [
        "GLD",
        "BIL",
        "TBT"
    ],

    "Emergency_Assets": [
        "SH",
        "TLT",
        "AGG",
        "SRS",
        "EFU",
        "TZA",
        "SDOW",
        "GLD",
        "BIL",
        "TBT"
    ],

    "Reference_RiskFree_Asset": [
        "^IRX"
    ],


    "sinceDate": "2003-01-31" if is_backtest else current_date,
    "untilDate": current_date if is_backtest else current_date, 
    "state": "",
    "Data_Source": "AlgoMart", # "StoredData", "AlphaVanatage", "Yahoo_Finanace", "AlgoMart"
    "Manual_Parameters_Entry": False   #False True
}





    #"assets": [
    #    "IWO", # "VBK"
    #    "ROBO",
    #    "QCLN",
    #    "ICLN",
    #    "VNQ",
    #    "IAU",
    #    "EDV",
    #    "SHV",
    #    "VCLT", #"IGLB", 
    #    "VCIT", #"LQD",  
    #    "ARKK",
    #    "VIG",
    #    "VCSH",
    #    "TLT",
    #    "SDY",
    #    "SPLG",
    #    "ARKW",
    #    "IJT",
    #    "MUB", # "SHM"
    #    "RSP", # "PRF"
    #    "HYG", # "ANGL"
    #    "EZU", # "IEUR"
    #    #"SHM",
    #    #"PRF",
    #    #"ANGL",
    #    #"IEUR",
    #    "SJNK",
    #    "RPG",
    #    "GVI",
    #    "PZA",
    #    "FPX",
    #    "SLYG",
    #    "RDVY",
    #    "EWL",
    #    "DES",
    #    "TLH",
    #    "FDL",
    #    "QQEW",
    #    "RPV",
    #    "IWC",
    #    "PTH",
    #    "IGBH",
    #    "KSA",
    #    "MLPX",
    #    "GTO",
    #    "EES",
    #    "EWD",
    #    "DWAS",
    #    "KIE",
    #    "FLEE",
    #    "RZV",
    #    "XSVM",
    #    "PXI",
    #    "TAN",
    #    "PBD",
    #    "SLX",
    #    "SOCL",
    #    "GRID",
    #    "DBC",
    #    "EWY",
    #    "EWN",
    #    "EWT",
    #    "GXC",
    #    "EFV",
    #    "FGD",
    #    "BWX",
    #    "HYEM",
    #    "UNG",
    #    "RWX",
    #    "KWEB",
    #    "CHIQ",
    #    "IGF",
    #    "NFRA",
    #    "FXI",
    #    "ASHR",
    #    "CQQQ",
    #    "CXSE",
    #    "PGJ",
    #    "VEU",
    #    "CWI",
    #    "EMGF",
    #    "AIA",
    #    "EPP",
    #    "GMF",
    #    "SPEM",
    #    "VYMI",
    #    "GEM",
    #    "DLS",
    #    "EFG",
    #    "VWOB",
    #    "DXJ",
    #    "HEWJ",
    #    "SPY",
    #    "VOO",
    #    "IVV",
    #    "VBMFX",
    #    "BND",
    #    "GBF",
    #    "SH",
    #    "TLT",
    #    "AGG",
    #    "EEV",
    #    "SRS",
    #    "EFU",
    #    "TZA",
    #    "SDOW",
    #    "GLD",
    #    "BIL",
    #    "TBT",
    #    "IEF",
    #    "EEM",

    #],
    # #"HYLD",






    #"assets": [
    #    "VBK",
    #    "ROBO",
    #    "QCLN",
    #    "ICLN",
    #    "VNQ",
    #    "IAU",
    #    "EDV",
    #    "SHV",
    #    "VCLT",
    #    "VCIT",
    #    "ARKK",
    #    "VIG",
    #    "VCSH",
    #    "TLT",
    #    "SDY",
    #    "SPLG",
    #    "ARKW",
    #    "IJT",
    #    "SHM",
    #    "PRF",
    #    "ANGL",
    #    "IEUR",
    #    "SJNK",
    #    "RPG",
    #    "GVI",
    #    "PZA",
    #    "FPX",
    #    "SLYG",
    #    "RDVY",
    #    "EWL",
    #    "DES",
    #    "TLH",
    #    "FDL",
    #    "QQEW",
    #    "RPV",
    #    "IWC",
    #    "PTH",
    #    "IGBH",
    #    "KSA",
    #    "MLPX",
    #    "GTO",
    #    "EES",
    #    "EWD",
    #    "DWAS",
    #    "KIE",
    #    "FLEE",
    #    "RZV",
    #    "XSVM",
    #    "PXI",
    #    "TAN",
    #    "PBD",
    #    "SLX",
    #    "SOCL",
    #    "GRID",
    #    "DBC",
    #    "EWY",
    #    "EWN",
    #    "EWT",
    #    "GXC",
    #    "EFV",
    #    "FGD",
    #    "BWX",
    #    "HYEM",
    #    "UNG",
    #    "RWX",
    #    "KWEB",
    #    "CHIQ",
    #    "IGF",
    #    "NFRA",
    #    "FXI",
    #    "ASHR",
    #    "CQQQ",
    #    "CXSE",
    #    "PGJ",
    #    "VEU",
    #    "CWI",
    #    "EMGF",
    #    "AIA",
    #    "EPP",
    #    "GMF",
    #    "SPEM",
    #    "VYMI",
    #    "GEM",
    #    "DLS",
    #    "EFG",
    #    "VWOB",
    #    "DXJ",
    #    "HEWJ",
    #    "SPY",
    #    "VOO",
    #    "IVV",
    #    "VBMFX",
    #    "BND",
    #    "GBF",
    #    "SH",
    #    "TLT",
    #    "AGG",
    #    "EEV",
    #    "SRS",
    #    "EFU",
    #    "TZA",
    #    "SDOW",
    #    "GLD",
    #    "BIL",
    #    "TBT",
    #    "IEF"
    #],
    # #"HYLD",



    #    "assets": [
    #    "IWO", # "VBK"
    #    "ROBO",
    #    "QCLN",
    #    "ICLN",
    #    "VNQ",
    #    "IAU",
    #    "EDV",
    #    "SHV",
    #    "IGLB", # "VCLT"
    #    "LQD", # "VCIT"
    #    "ARKK",
    #    "SCHD", # "VIG"
    #    "SHY", # "VCSH"
    #    "TLT",
    #    "DVY", # "SDY"
    #    "SPLG",
    #    "ARKW",
    #    "IJT",
    #    "MUB", # "SHM"
    #    "RSP", # "PRF"
    #    "HYG", # "ANGL"
    #    "EZU", # "IEUR"
    #    "SJNK",
    #    "RPG",
    #    "GVI",
    #    "FPX",
    #    "SLYG",
    #    "FVD", # "RDVY"
    #    "EWU", # "EWD"
    #    "DES",
    #    "TLH",
    #    "FDL",
    #    "QQEW",
    #    "RPV",
    #    "IWC",
    #    "PTH",
    #    "KSA",
    #    "AMLP", # "MLPX"
    #    "BND", # "GTO"
    #    "EES",
    #    "DWAS",
    #    "KIE",
    #    "FEZ", # "FLEE"
    #    "RZV",
    #    "IJS", # "XSVM"
    #    "XLE", # "PXI"
    #    "TAN",
    #    #"FDN", # "SOCL"
    #    "GRID",
    #    "DBC", # "COM"
    #    "EWY",
    #    "EWN",
    #    "EWT",
    #    "FXI", # "GXC"
    #    "EFV",
    #    "FGD",
    #    "BWX",
    #    "HYEM",
    #    "UNG",
    #    "VNQI", # "RWX"
    #    "KWEB",
    #    "CHIQ",
    #    "IGF", # "NFRA"
    #    "ASHR",
    #    "CQQQ",
    #    "MCHI", # "CXSE"
    #    "PGJ",
    #    "VEU",
    #    "CWI",
    #    "EMGF",
    #    "AAXJ", # "AIA"
    #    "EPP",
    #    "VPL", # "GMF"
    #    "EEM", # "SPEM"
    #    #"VWO", # "GEM"
    #    "DLS",
    #    "EFG",
    #    "EMB", # "VWOB"
    #    "DXJ",
    #    "EWJ", # "HEWJ"
    #    "SPY",
    #    "VOO",
    #    "IVV",
    #    "VBMFX",
    #    "GBF",
    #    "SH",
    #    "AGG",
    #    "SRS",
    #    "EFU",
    #    "TZA",
    #    "SDOW",
    #    "GLD",
    #    "BIL",
    #    "TBT",
    #    "IEF",
    #    "SLX"
    #],

        
    #    "IWO", # "VBK"
    #    "ROBO",
    #    "QCLN",
    #    "ICLN",
    #    "VNQ",
    #    "IAU",
    #    "EDV",
    #    "SHV",
    #    "IGLB", # "VCLT"
    #    "LQD", # "VCIT"
    #    "ARKK",
    #    "SCHD", # "VIG"
    #    "SHY", # "VCSH"
    #    "DVY", # "SDY"
    #    "SPLG",
    #    "ARKW",
    #    "IJT",
    #    "MUB", # "SHM"
    #    "RSP", # "PRF"
    #    "HYG", # "ANGL"
    #    "EZU", # "IEUR"
    #    "SJNK",
    #    "RPG",
    #    "GVI",
    #    "FPX",
    #    "SLYG",
    #    "FVD", # "RDVY"
    #    "EWU", # "EWD"
    #    "DES",
    #    "TLH",
    #    "FDL",
    #    "QQEW",
    #    "RPV",
    #    "IWC",
    #    "PTH",
    #    "KSA",
    #    "AMLP", # "MLPX"
    #    "EES",
    #    "DWAS",
    #    "KIE",
    #    "FEZ", # "FLEE"
    #    "RZV",
    #    "IJS", # "XSVM"
    #    "XLE", # "PXI"
    #    "TAN",
    #    "GRID",
    #    "DBC", # "COM"
    #    "EWY",
    #    "EWN",
    #    "EWT",
    #    "FXI", # "GXC"
    #    "EFV",
    #    "FGD",
    #    "BWX",
    #    "HYEM",
    #    "UNG",
    #    "VNQI", # "RWX"
    #    "KWEB",
    #    "CHIQ",
    #    "IGF", # "NFRA"
    #    "ASHR",
    #    "CQQQ",
    #    "MCHI", # "CXSE"
    #    "PGJ",
    #    "VEU",
    #    "CWI",
    #    "EMGF",
    #    "AAXJ", # "AIA"
    #    "EPP",
    #    "VPL", # "GMF"
    #    "DLS",
    #    "EFG",
    #    "DXJ",
    #    "EWJ", # "HEWJ"
    #    "BND", # Keep as specified
    #    "SPY", # Keep as specified
    #    "VOO", # Keep as specified
    #    "IVV", # Keep as specified
    #    "SLX"
